name: TEST-ACTION

on:
  push:
    branches: [pj]
  workflow_dispatch: # Ceci ajoute un bouton pour lancer manuellement

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Le workflow fonctionne sur la branche pj !"